export const CREATE_AUTHOR='CREATE_AUTHOR';
export const LOAD_AUTHORS_SUCCESS='LOAD_AUTHORS_SUCCESS';
export const LOAD_COURSES_SUCCESS='LOAD_COURSES_SUCCESS';
export const SAVE_AUTHOR_SUCCESS = 'SAVE_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_OPTIMISTIC = 'DELETE_AUTHOR_OPTIMISTIC';